CREATE DATABASE demo_db;

CREATE TABLE IF NOT EXISTS Schedule
( id INTEGER NOT NULL AUTO_INCREMENT,
  dutyDate VARCHAR(255) NOT NULL,
  targetUser VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
( id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  birthday VARCHAR(255) NOT NULL,
  duty VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);